### ISSUE TITLE
Did Xdelta patch receive the bugfix?

### ISSUE THREAD

**Issue by littlelum** [Gota7/MoreObjectsMod#1]
Hi, I noticed that there was some changes relating to the launch star crash and gravity modifier update, but the XDelta folder wasn't changed, it just says that it was the initial release. Will the XDelta patch version also get this change?
Thanks, and sorry for the (potentially) dumb question.

**Comment by SplattyDS** [comment]
The patch (MOM.xdelta) was updated, the XDelta folder contains the version of XDelta that was used to create the patch.

**Comment by Gota7** [comment]
If you look at the latest commit (https://github.com/Gota7/MoreObjectsMod/commit/dc917024541654eb694639b376ba6dd6d3b1dceb), you will see that the XDELTA was update along with everything else needed for the update.
